---
default: &default
  public_folder: frontend/assets
  views_folder: frontend/views
  documents_dir: doc/api
  migrations_dir: db/migrations
  fixtures_dir: spec/fixtures
  paginate_per_page: 25
  http_cache: on
  hostname: localhost
  protocol: http
  port: 3000

production:
  <<: *default
  port: 443
  protocol: https

development:
  <<: *default

test:
  <<: *default
  port: 3030
