#!/bin/bash -i

install() {
  CHECK_GIT_STATUS=0

  for file in $FILES; do
    local tname=$(target_name "$file")
    TARGET_FILE="$TARGET_DIR/$tname"
    if [ -f "$TARGET_FILE" ]; then
      rm "$file"
      ln "$TARGET_FILE" "$file"

      if [ -n "$(git status --porcelain "$file")" ]; then
        echo "Target file '$TARGET_FILE' already exist and differs against repo!"
        CHECK_GIT_STATUS=1
      fi
    else
      echo "Linking '$TARGET_FILE'"
      ln "$file" "$TARGET_FILE"
    fi
    config_add "$file" "$TARGET_FILE"
  done

  if [ $CHECK_GIT_STATUS -gt 0 ]; then
    echo ""
    git status
  fi
}
