#!/bin/bash -i

reset() {
  for file in $FILES; do
    file=${file##*/}
    if [ -n "$(git status --porcelain "files/$file")" ]; then
      git diff "files/$file"
      echo -en "\nDo you want to discard these changes (y/N)? "
      read -e discard
      discard=${discard,,} # Lower case
      if [[ ! "$discard" =~ ^y.* ]]; then
        continue
      fi
    fi

    git checkout -- "files/$file"
  done
}
