#!/bin/bash -i


reset() {
  local linked=$(find files/ -type f -printf '%n %f\n' | sed '/^1 /d;s/^[0-9]* //')

  for file in $FILES; do
    file=${file##*/}
    if [ -n "$(git status --porcelain "files/$file")" ]; then
      git diff "files/$file"
      echo -en "\nDo you want to discard these changes (y/N)? "
      read -e discard
      discard=${discard,,} # Lower case
      if [[ ! "$discard" =~ ^y.* ]]; then
        continue
      fi
    fi

    git checkout -- "files/$file"

    if [[ "$linked" =~ "$file" ]]; then
      local log=$(logfile $file)
      if [ -f $log ]; then
        for target in $(cat $log); do
          if [ -f "$target" ]; then
            rm "$target"
            ln "files/$file" "$target"
          fi
        done
      fi
    fi
  done
}
