#!/bin/bash -i

status() {
  echo "Linked:"
  find files/ -type f -printf '%n %f\n' | awk '$1 > 1 {print $2}' | while IFS= read -r name; do
    local targets=$(config_targets "$name" | tr '\n' ' ')
    echo "  $name -> ${targets% }"
  done

  echo -e "\nUnlinked:"
  find files/ -type f -printf '%n %f\n' | awk '$1 == 1 {print "  " $2}'
}
