#!/bin/bash -i

uninstall() {
  for file in $FILES; do
    if [ -n "$(git status --porcelain "$file")" ]; then
      echo -e "$file has been changed.\n"
      git diff $file
    fi

    local source_name="${file##*/}"
    local targets
    mapfile -t targets < <(config_targets "$source_name")
    for target in "${targets[@]}"; do
      if [ -L "$target" ]; then
        echo "Unlinking '$target'"
        rm "$target"
        cp "$file" "$target"
      fi
      config_remove "$source_name" "$target"
    done
  done
}
