#!/bin/bash -i

uninstall() {
  for file in $FILES; do
    if [ -n "$(git status --porcelain "$file")" ]; then
      echo -e "$file has been changed.\n"
      git diff $file
    fi

    echo "Unlinking '$file'"
    # Removing the file will delete the hard link.
    rm -f $file
    # Then simply checkout the file to restore it without the link
    git checkout -- $file

    local log=$(logfile $file)
    if [ -f $log ]; then
      for target in $(cat $log); do
        if [ -f $target ]; then
          rm -i $target
        fi
      done
      rm $log
    fi
  done
}
