#!/bin/bash -i

uninstall() {
  for file in $FILES; do
    if [ -n "$(git status --porcelain "$file")" ]; then
      echo -e "$file has been changed.\n"
      git diff $file
    fi

    echo "Unlinking '$file'"
    rm -f $file
    git checkout -- $file

    local source_name="${file##*/}"
    local targets
    mapfile -t targets < <(config_targets "$source_name")
    for target in "${targets[@]}"; do
      if [ -f "$target" ]; then
        rm -i "$target"
      fi
      config_remove "$source_name" "$target"
    done
  done
}
