#!/bin/bash -i

update() {
  local linked_before=$(find files/ -type f -printf '%n %f\n' | sed '/^1 /d;s/^[0-9]* //')
  git pull
  local unlinked_after=$(find files/ -type f -printf '%n %f\n' | sed -n '/^1 /!d;s/^[0-9]* //p')

  for file in $linked_before; do
    if [[ "$unlinked_after" =~ "$file" ]]; then
      local log="${LOG_DIR}/$file"
      if [ -f $log ]; then
	for target in $(cat $log); do
	  if [ -f $target ]; then
	    rm "files/$file"
	    ln "$target" "files/$file"
	  else
	    sed -i "\:$target:d" $log
	    if [ ! -s $log ]; then
	      rm $log
	    fi
	  fi
	done
      fi
    fi
  done
}
