# This file is public!
# Put things that should be private in ~/.bash_local_aliases

if [ -f ~/.bash_local_aliases ]; then
    . ~/.bash_local_aliases
fi

alias ll='ls -l'
alias la='ls -A'
alias lh='ls -lh'
alias li='ls -li'
alias igrep='grep -i'
alias less='less -I'

alias cdgems='cd $(gem environment gemdir)/gems'
alias be='bundle exec'
alias json='ruby -rjson -e "puts (JSON.pretty_generate JSON.parse(STDIN.read))"'
alias gm='git checkout master'

alias db='docker build . -t'
alias dr='docker run --rm -it'
alias de='docker exec -it'
