" Auto-install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

call plug#begin()
"Language pack
Plug 'sheerun/vim-polyglot'

" Unix shell commands
Plug 'tpope/vim-eunuch'

"Universal defaults
Plug 'tpope/vim-sensible'

"Adjust shiftwidth and expandtab
" Plug 'tpope/vim-sleuth'

"Git
Plug 'tpope/vim-fugitive'

"Rails
Plug 'tpope/vim-rails'

"Toggle comments
Plug 'tpope/vim-commentary'

"Change surrounding chars of a word
Plug 'tpope/vim-surround'

" Run things async and populate the quickfix list
Plug 'tpope/vim-dispatch'

"Database interactions
" Plug 'tpope/vim-dadbod'

"Syntax check
" Plug 'scrooloose/syntastic'
Plug 'dense-analysis/ale'

"Rspec
" Plug 'thoughtbot/vim-rspec'

" Test runners
Plug 'vim-test/vim-test'

"Split/join statements
Plug 'AndrewRadev/splitjoin.vim'

"Jump between lines depending on indentation
Plug 'jeetsukumaran/vim-indentwise'

"Solarized color scheme
Plug 'altercation/vim-colors-solarized'

" highlight characteres to jump to when using f,F,t and T
Plug 'unblevable/quick-scope'

" Smart subsitutions (:Subvert)
Plug 'tpope/vim-abolish'

" Vim motions on speed!
Plug 'easymotion/vim-easymotion'
"
" Vim REST Control
Plug 'diepm/vim-rest-console'

" JavaScript support
Plug 'pangloss/vim-javascript'

" TypeScript syntax
" Plug 'leafgarland/typescript-vim'

" JS and JSX syntax
Plug 'maxmellon/vim-jsx-pretty'

" Code completions
" Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Context dependent comments (e.g in .vue files)
" Plug 'suy/vim-context-commentstring'

" Vim syntax and indent plugin for .vue files
Plug 'leafOfTree/vim-vue-plugin'

" GraphQL syntax highlight and indentation
" Plug 'jparise/vim-graphql'
"
" Easy locale lookup in Rails i18n.
Plug 'airblade/vim-localorie'

" Fuzzy finder
Plug 'vim-fuzzbox/fuzzbox.vim'

call plug#end()

" enable all features
set nocompatible

" Wrap too long lines
set wrap

" Tabs are 2 characters
set tabstop=2
set softtabstop=2

" (Auto)indent uses 2 characters
set shiftwidth=2

" spaces instead of tabs
set expandtab

set pastetoggle=<C-u>
set showmode

" guess indentation
set autoindent

" Expand the command line using tab
set wildchar=<Tab>
set wildcharm=<Tab>

" show line numbers
set number

" powerful backspaces
set backspace=indent,eol,start

" highlight the searchterms
set hlsearch

" jump to the matches while typing
set incsearch

" ignore case while searching
set ignorecase

" don't wrap words
set textwidth=0

" history
set history=50

" 1000 undo levels
set undolevels=1000

" show partial commands
set showcmd

" show matching braces
set showmatch

" write before hiding a buffer
set autowrite

" auto-detect the filetype
filetype plugin indent on

" syntax highlight
syntax on

"Ignore case
set ic

" Smartcase search. If any character is a Capital, search is case sensitive
set scs

" Always show the menu, insert longest match
set completeopt=menuone,longest

"Open new buffers in a new tab
" set switchbuf=usetab,newtab

" Search recursive (e.g. :find SOME_FI <TAB>)
set path+=**

" Exclude node_modules/ for search, like :find or :tabfind
set wildignore+=*/node_modules/*

" Exclude some more paths
set wildignore+=sorbet/**,system/**,log/**,tmp/**

"
set clipboard=unnamedplus

"
set splitbelow
set splitright

" Create session files
set sessionoptions=buffers,curdir,folds,tabpages

autocmd FileType html setlocal sw=2 sts=2 et
autocmd FileType ruby setlocal sw=2 sts=2 et suffixesadd+=.rb
autocmd FileType eruby setlocal sw=2 sts=2 et
" autocmd FileType yaml setlocal foldmethod=indent

" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid, when inside an event handler
" (happens when dropping a file on gvim) or for git commit messages.
autocmd BufReadPost *
  \ if &ft !~# 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

" turn on for markdown files and text files
autocmd BufRead,BufNewFile *.md setlocal spell
autocmd BufRead,BufNewFile *.txt setlocal spell

augroup TypeScriptFiles
  " GoTo code navigation.
  au FileType typescript,vue nmap <silent> gd <Plug>(coc-definition)
  au FileType typescript,vue nmap <silent> gr <Plug>(coc-references)
augroup END

augroup NewVueVile
  autocmd!
  " Create new Vue files from template
  au BufNewFile *.vue 0r ~/.vim/templates/vue
augroup END

autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

autocmd BufEnter * stopinsert

" Disable paste mode when leaving Insert Mode
autocmd InsertLeave * set nopaste

" vim-localorie: Always show full path in locales files
autocmd CursorMoved *.yml echo localorie#expand_key()

let mapleader = ','
nnoremap <leader>c :call g:ToggleQuickfix()<CR>
nnoremap <leader>n :set number!<CR>
nnoremap <leader>m :nohlsearch<CR>
nnoremap <leader>h :nohlsearch<CR>
nnoremap <leader>rh :set cursorline!<CR>
nnoremap <leader>b f,2lXi<CR><Esc>
nnoremap <leader>d :call RailsDbSchema()<CR>
nnoremap <leader>q :call RailsRoutes()<CR>
nnoremap <leader>i :call RailsLocales()<CR>
nnoremap <leader>hr :set cursorline!<CR>
nnoremap <leader>hc :call g:ToggleColorColumn()<CR>
nnoremap <leader>a :G blame<CR>
nnoremap <leader>ga yiw:Ggrep! <C-R>" app/<CR>
nnoremap <leader>gg yiw:Ggrep! <C-R>"<CR>
vmap     <leader>ga y:Ggrep! "<C-R>"" app/<CR>
vmap     <leader>gg y:Ggrep! "<C-R>""<CR>
nnoremap <leader>rts 'T:call RunNearestSpec()<CR>
nnoremap <leader>x :source $MYVIMRC<CR>
nnoremap <leader>l :ALEToggle<CR>

nnoremap <leader>j <Cmd>call GoToNextIndent(1, v:count1)<CR>
nnoremap <leader>k <Cmd>call GoToNextIndent(-1, v:count1)<CR>
vmap <leader>j <Cmd>call GoToNextIndent(1, v:count1)<CR>
vmap <leader>k <Cmd>call GoToNextIndent(-1, v:count1)<CR>

" Faster movement with Ctrl
nnoremap <C-J> 5j
nnoremap <C-K> 5k
nnoremap <C-Down> 5j
nnoremap <C-Up> 5k

" Open file relative to current file
nnoremap <leader>e :e <C-R>=expand("%:p:h") . "/" <CR>
nnoremap <leader>t :tabe <C-R>=expand("%:p:h") . "/" <CR>
nnoremap <leader>s :split <C-R>=expand("%:p:h") . "/" <CR>
nnoremap <leader>v :vsplit <C-R>=expand("%:p:h") . "/" <CR>
" nnoremap <leader>d :vsplit<CR><C-W>h<C-O>
cnoremap <expr> %% getcmdtype() == ':' ? expand('%:h').'/' : '%%'

nnoremap <leader>] :tab tag <C-R><C-W><CR>

"Highlight current word without jumping to next
nnoremap <leader>* *N

" Easymotion
map  <Leader>w <Plug>(easymotion-bd-w)
nmap <Leader>w <Plug>(easymotion-overwin-w)

" " Rspec
" nnoremap <leader>rf :w<CR>:call RunCurrentSpecFile()<CR>
" nnoremap <leader>rs :w<CR>:call RunNearestSpec()<CR>
" nnoremap <leader>rl :w<CR>:call RunLastSpec()<CR>
" nnoremap <leader>ra :w<CR>:call RunFailedSpecs()<CR>

" vim-test
nnoremap <leader>rdf :w<CR>:TestFile<CR>
nnoremap <leader>rds :w<CR>:TestNearest<CR>
nnoremap <leader>rdl :w<CR>:TestLast<CR>
nnoremap <leader>rf :w<CR>:TestFile -strategy=basic<CR>
nnoremap <leader>rs :w<CR>:TestNearest -strategy=basic<CR>
nnoremap <leader>rl :w<CR>:TestLast -strategy=basic<CR>

" vim-localorie
nnoremap <silent> <leader>lt :call localorie#translate()<CR>
nnoremap <silent> <leader>le :echo localorie#expand_key()<CR>
autocmd CursorMoved *.yml echo localorie#expand_key()

let maplocalleader = '-'
nnoremap <buffer> <LocalLeader>t gg/\v^(class\|module)<CR>zt

" Change current directory to the same as current file
" set autochdir
" autocmd BufEnter * silent! lcd %:p:h

"Ctags
set tags+=./.ctags,.git/tags
"Open the definition in a new tab
nnoremap <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>
"Open the definition in a vertical split
nnoremap <A-\> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>

"Map gl to Go to end of line
nnoremap gh ^
nnoremap ga $

" Insert a new line before/after current row
nnoremap [<Space> O<Esc>j
nnoremap ]<Space> o<Esc>k

"Map Ctrl h/l to previous/next tab
nnoremap <C-h> :tabp<CR>
nnoremap <C-a> :tabn<CR>
nnoremap <C-Left>  :tabp<CR>
nnoremap <C-Right> :tabn<CR>

" Increment/decrement numbers
nnoremap + <C-a>
nnoremap - <C-x>

" Toggle last buffer
nnoremap <C-t> :b #<CR>

"" in visual mode, search selection up or down
vnoremap * y/<C-R>"<CR>
vnoremap # y?<C-R>"<CR>

cmap w!! w !sudo tee > /dev/null %

" No more Ex mode
map Q <Nop>

iab frozstr # frozen_string_literal: true
iab vuet :0r ~/.vim/templates/vue

function! g:ToggleQuickfix()
  for buffer in tabpagebuflist()
    if bufname(buffer) == ''
      " then it should be the quickfix window
      cclose
      return
    endif
  endfor

  botright copen
endfunction

function! g:ToggleColorColumn()
  if &l:colorcolumn != ''
    let &l:colorcolumn=''
  else
    let &l:colorcolumn=col('.')
  endif
endfunction

function! RailsDbSchema()
  let l:git_dir = system("git rev-parse --show-toplevel")
  let l:file = substitute(l:git_dir, '\n$', '/db/schema.rb', '')
  " let l:file = substitute(l:git_dir, '\n$', '/db/structure.sql', '')
  :exec("0tabedit ".expand(l:file))
endfunction

function! RailsRoutes()
  let l:git_dir = system("git rev-parse --show-toplevel")
  let l:file = substitute(l:git_dir, '\n$', '/config/routes.rb', '')
  :exec("0tabedit ".expand(l:file))
endfunction

function! RailsLocales()
  let l:git_dir = system("git rev-parse --show-toplevel")
  let l:dir = substitute(l:git_dir, '\n$', '/config/locales/', '')
  :exec("0tabedit ".expand(l:dir . 'en.yml'))
  :exec("vsplit ".expand(l:dir . 'sv.yml'))
endfunction

function! BufSel(pattern)
  let bufcount = bufnr("$")
  let currbufnr = 1
  let nummatches = 0
  let firstmatchingbufnr = 0
  while currbufnr <= bufcount
    if(bufexists(currbufnr))
      let currbufname = bufname(currbufnr)
      if(match(currbufname, a:pattern) > -1)
        echo currbufnr . ": ". bufname(currbufnr)
        let nummatches += 1
        let firstmatchingbufnr = currbufnr
      endif
    endif
    let currbufnr = currbufnr + 1
  endwhile
  if(nummatches == 1)
    execute ":buffer ". firstmatchingbufnr
  elseif(nummatches > 1)
    let desiredbufnr = input("Enter buffer number: ")
    if(strlen(desiredbufnr) != 0)
      execute ":buffer ". desiredbufnr
    endif
  else
    echo "No matching buffers"
  endif
endfunction

function! GoToNextIndent(inc, count)
    let currentPos = getpos('.')
    let currentLine = currentPos[1]
    let matchIndent = 0
    let found = 0

    while found < a:count && currentLine != line('$') + 1 && currentLine != -1
        let currentLine += a:inc
        let matchIndent = indent(currentLine) == indent('.')
        if matchIndent
            let found += 1
            if found < a:count
                let matchIndent = 0
            endif
        endif
    endwhile

    if (found == a:count)
        let currentPos[1] = currentLine
        call setpos('.', currentPos)
    endif
endfunction

" function! GoToNextIndent(inc)
"     " Get the cursor current position
"     let currentPos = getpos('.')
"     let currentLine = currentPos[1]
"     let matchIndent = 0

"     " Look for a line with the same indent level whithout going out of the buffer
"     while !matchIndent && currentLine != line('$') + 1 && currentLine != -1
"         let currentLine += a:inc
"         let matchIndent = indent(currentLine) == indent('.')
"     endwhile

"     " If a line is found go to this line
"     if (matchIndent)
"         let currentPos[1] = currentLine
"         call setpos('.', currentPos)
"     endif
" endfunction

" " Make sure highlight search foreground color is displayable on Yellow
" highlight Search term=reverse ctermbg=11 ctermfg=Black guibg=Yellow

" Code Lint
" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 2
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0
" let g:syntastic_ruby_checkers = ['rubocop']
" let g:syntastic_javascript_checkers = ['eslint']
" let g:syntastic_javascript_eslint_exe = '$(npm bin)/eslint'
" let g:syntastic_scss_checkers = ['scss_lint']
" let g:syntastic_debug = 33
"let g:syntastic_loc_list_height = 3

let g:ale_set_highlights = 0
let g:ale_virtualtext_cursor = 0
let g:ale_linters_explicit = 1
let g:ale_linters= {'ruby': ['standardrb'], 'typescript': ['eslint'], 'vue': ['eslint']}
let g:ale_fixers = {'ruby': ['standardrb'], 'typescript': ['eslint'], 'vue': ['eslint']}
" This does not seem to work. How to stop tsserver from showing warnings that
" eslint don't care about???
let b:ale_linters_ignore = ['tsserver']

augroup SpellUnderline
  autocmd!
  autocmd ColorScheme * highlight SpellBad cterm=underline
augroup END

let g:solarized_termcolors=256
colorscheme solarized

let theme = system('gsettings get org.gnome.desktop.interface color-scheme')
if theme =~? 'dark'
  set background=dark
else
  set background=light
endif


let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']

" if &diff
"   highlight DiffAdd    cterm=BOLD ctermfg=NONE ctermbg=22
"   highlight DiffDelete cterm=BOLD ctermfg=NONE ctermbg=52
"   highlight DiffChange cterm=BOLD ctermfg=NONE ctermbg=23
"   highlight DiffText   cterm=BOLD ctermfg=NONE ctermbg=24
" endif

let g:netrw_liststyle = 1

" Fix long file names being smashed together with file size
let g:netrw_dynamic_maxfilenamelen = 32

" Added git branch to status line
set statusline=%<%{fugitive#statusline()}\ 
set statusline+=%f\ 
set statusline+=%h%m%r
set statusline+=%q
set statusline+=[Buf:%n]
set statusline+=%=
set statusline+=%-14.(%l,%c%V%)\ 
set statusline+=%P

" CoC extensions
let g:coc_global_extensions = ['coc-tsserver']

" Run vim-test tests via vim-dispatch
let test#strategy = "dispatch"

function! BufSel(pattern)
  let bufcount = bufnr("$")
  let currbufnr = 1
  let nummatches = 0
  let firstmatchingbufnr = 0
  while currbufnr <= bufcount
    if(bufexists(currbufnr))
      let currbufname = bufname(currbufnr)
      if(match(currbufname, a:pattern) > -1)
        echo currbufnr . ": ". bufname(currbufnr)
        let nummatches += 1
        let firstmatchingbufnr = currbufnr
      endif
    endif
    let currbufnr = currbufnr + 1
  endwhile

  if(nummatches == 1)
    return firstmatchingbufnr
  elseif(nummatches > 1)
    let desiredbufnr = input("Enter buffer number: ")
    if(strlen(desiredbufnr) != 0)
      return desiredbufnr
    endif
  else
    return -1
  endif
endfunction

function! BufOpen(pattern)
  let matchnr = BufSel(a:pattern)
  if(matchnr < 0)
    echo "No buffers match: " . a:pattern
  else
    execute ":buffer ". matchnr
  endif
endfunction

function! BufTabOpen(pattern)
  let matchnr = BufSel(a:pattern)
  if(matchnr < 0)
    echo "No buffers match: " . a:pattern
  else
    execute ":tab sb ". matchnr
  endif
endfunction

"Bind the Buf**() functions to user-commands
command! -nargs=1 Bs :call BufSel("<args>")
command! -nargs=1 Bo :call BufOpen("<args>")
command! -nargs=1 Bt :call BufTabOpen("<args>")

command! GHurl echo "https://github.com/apoex/auti/blob/master/" . expand('%') . "#L" . line('.')

" vim-vue-plugin: set local options based on syntax
function! OnChangeVueSyntax(syntax)
  " echom 'Syntax is '.a:syntax
  if a:syntax == 'html'
    setlocal commentstring=<!--%s-->
    setlocal comments=s:<!--,m:\ \ \ \ ,e:-->
  elseif a:syntax =~ 'css'
    setlocal comments=s1:/*,mb:*,ex:*/ commentstring&
  else
    setlocal commentstring=//%s
    setlocal comments=sO:*\ -,mO:*\ \ ,exO:*/,s1:/*,mb:*,ex:*/,://
  endif
endfunction
